fixing `test_add_environment_with_real_conda_manager` -- using the asmeurer leads to older versions of ncurses which causes with py2.7/conda errors:
>Error: ERROR: placeholder ... too short in: ncurses-5.9-1